export const actionEnum = {
    AUTH_START: 'AUTH_START',
    AUTH_SUCCESS: 'AUTH_SUCCESS',
    AUTH_FAIL: 'AUTH_FAIL',

    POST_UPLOAD_START: ' POST_UPLOAD_START',
    POST_UPLOAD_SUCCESS: ' POST_UPLOAD_SUCCESS',
    POST_UPLOAD_FAIL: ' POST_UPLOAD_FAIL',
};